# Configuration schema for shp_custom module

shp_custom.settings:
  type: mapping
  label: 'Shepherd settings'
  mapping:
    ldap:
      type: mapping
      label: 'LDAP Integration'
      mapping:
       enabled:
        type: boolean
        label: 'Enabled'
    controlled_roles:
      type: mapping
      label: 'Controlled Roles'
      mapping:
        administrator:
          type: string
          label: 'Administrator'
        shp_developer:
          type: string
          label: 'Developer'
        shp_online_consultant:
          type: string
          label: 'Online Consultant'
        shp_site_administrator:
          type: string
          label: 'Site Administrator'
        shp_web_author:
          type: string
          label: 'Web Author'
        shp_content_editor:
          type: string
          label: 'Content Editor'
    backup_service:
      type: mapping
      label: 'Backup Service'
      mapping:
        path:
          type: string
          label: 'Backup path'
    environment_domains:
      type: mapping
      label: 'Environments and Domains'
      mapping:
        prd:
          type: string
          label: 'adelaide.edu.au'
        stg:
          type: string
          label: 'stg.adelaide.edu.au'
        uat:
          type: string
          label: 'uat.adelaide.edu.au'
        dev:
          type: string
          label: 'test'
