# Configuration schema for shp_custom module

shp_custom.settings:
  type: mapping
  label: 'Shepherd settings'
  mapping:
    backup_service:
      type: mapping
      label: 'Backup Service'
      mapping:
        path:
          type: string
          label: 'Backup path'
    environment_domains:
      type: mapping
      label: 'Environments and Domains'
      mapping:
        prd:
          type: string
          label: 'adelaide.edu.au'
        stg:
          type: string
          label: 'stg.adelaide.edu.au'
        uat:
          type: string
          label: 'uat.adelaide.edu.au'
        dev:
          type: string
          label: 'test'
