# Configuration schema for shp_custom module

shp_custom.settings:
  type: mapping
  label: 'Shepherd settings'
  mapping:
    backup_service:
      type: mapping
      label: 'Backup Service'
      mapping:
        path:
          type: string
          label: 'Backup path'
